[package]
name = "tunnel-hub"
version = "0.1.2"
description = "SSH Tunnel Manager"
authors = ["zeptools"]
edition = "2021"

[lib]
name = "tunnel_hub_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-ico", "image-png", "tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
russh = { version = "0.57", default-features = false, features = ["flate2", "ring", "rsa"] }
uuid = { version = "1", features = ["v4"] }
log = "0.4"
env_logger = "0.11"
chrono = { version = "0.4", features = ["serde"] }
tokio-util = "0.7"
anyhow = "1"
tauri-plugin-autostart = "2.5.1"
regex = "1.12.3"
